[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
solc_version = '0.8.23'

[invariant]
runs = 32
depth = 100
fail_on_revert = true

# See more config options https://book.getfoundry.sh/reference/config/
